### ISSUE TITLE
StackOverflowException shortly after creating a new world

### ISSUE THREAD

**Issue by Leo40Git** [Team-RAM/RAM#40] opened 2020-03-29 10:58 UTC
1. Create a new world.
2. Wait for the world to finish generation.
3. The game will now enter the world.
4. Wait a bit.
5. **_CRASH!_**

[crash-2020-03-29_10.54.09-server.txt](https://github.com/Team-RAM/RAM/files/4398673/crash-2020-03-29_10.54.09-server.txt)

**Comment by Darkere** [comment] 2020-03-29 11:01
Probably a duplicate of #31

You should be able to restart and load the world after this (Or generate a different world with a different seed).

Possibly fixed in the next version.

**Closed as completed by Darkere** 2020-03-29 11:01 UTC
